image:
  file: .gitpod.Dockerfile
tasks:
  - name: Starting Project
    init: cp .env.example .env &&
      sed -i "s|APP_URL=|APP_URL=${GITPOD_WORKSPACE_URL}|g" .env &&
      sed -i "s|APP_URL=https://|APP_URL=https://8000-|g" .env &&
    command: composer install &&
      php artisan storage:link &&
      php artisan key:generate &&
      php artisan serve
ports:
  - port: 8000
    onOpen: open-browser
vscode:
  extensions:
    - bmewburn.vscode-intelephense-client
    - MehediDracula.php-namespace-resolver
    - junstyle.php-cs-fixer
